#!/usr/bin/env bash
set -euo pipefail

export PORT="${PORT:-3011}"
export INVOICE_REPOSITORY="${INVOICE_REPOSITORY:-memory}"
export DYNAMO_MOCK="${DYNAMO_MOCK:-true}"
export ENABLED_PAYMENT_PROVIDERS="${ENABLED_PAYMENT_PROVIDERS:-ASAAS}"
export DEFAULT_PAYMENT_PROVIDER="${DEFAULT_PAYMENT_PROVIDER:-ASAAS}"
export ASAAS_MOCK="${ASAAS_MOCK:-true}"
export WEBHOOK_PROCESSING_MODE="${WEBHOOK_PROCESSING_MODE:-sync}"
export DD_TRACE_ENABLED="${DD_TRACE_ENABLED:-false}"
export DD_LOGS_INJECTION="${DD_LOGS_INJECTION:-false}"
export DD_RUNTIME_METRICS_ENABLED="${DD_RUNTIME_METRICS_ENABLED:-false}"

npm run start
